// Rule-based "Análises estratégicas" engine. This is deliberately NOT an LLM
// call — there's no generative AI model configured in this deployment (no
// provider API key, no backend route for it — see IntegrationsPanel.tsx for
// what's missing to activate one). Every sentence here is generated by
// inspectable statistical rules over the numbers already on screen, and the
// UI must always label it as such rather than presenting it as if an AI had
// written it.
//
// The rules this file exists to enforce (see the brief this engine was
// built against):
//  - Compare a campaign only against other campaigns of the SAME client and
//    a COMPATIBLE objective — never against a global total that blends
//    different clients or different kinds of campaigns.
//  - Never judge an awareness/reach campaign mainly by cost-per-conversation
//    (or any click-based rate) — use the indicator that actually matches
//    what the campaign is optimizing for.
//  - Never read a budget difference between two different clients as one
//    operation's "concentration problem" — concentration is only evaluated
//    within a single client's own campaigns.
//  - Never flag "100% of investment" as a finding when the user has simply
//    filtered the view down to one campaign — concentration needs at least
//    two campaigns to compare within the same client.
//  - Never call a result "vencedora"/best from an isolated, low-volume
//    sample — every comparison is gated on minimum impressions/clicks/
//    conversations, spend share, AND period length.
//  - Never present a budget increase/decrease as a definitive conclusion —
//    at most a hypothesis with a suggested test and an indicator to watch.
//  - Never infer sales, revenue, profit, ROI, or commercial quality from
//    clicks or conversations alone — those numbers measure delivery/
//    engagement, not business outcome.
//  - Never invent goals, benchmarks, or market context that don't exist in
//    this data — every comparison baseline is computed from the same
//    filtered scope, never an external number.

import type { CampaignInsight } from "./meta-ads-types";
import { sumTotals, ctr, cpc, cpm, costPerConversation, pctChange, type Totals } from "./metrics";
import { formatCurrencyBRL, formatInteger, formatPercent, formatSignedPercent, formatShortDate } from "./format";
import { objectiveGroup, OBJECTIVE_GROUP_LABEL, type ObjectiveGroup, type KpiId } from "./kpi-hierarchy";

export type InsightEvidence = { label: string; value: string };

export type InsightItem = {
  /** Interpretation in plain language — numeric evidence is embedded inline, structured evidence is also below in `evidence`. */
  text: string;
  evidence: InsightEvidence[];
  /** The period this finding's evidence covers (almost always the report's own period, except a single-day spike). */
  period: string;
  /** The limitation or hypothesis relevant to THIS specific finding — never a generic disclaimer copy-pasted everywhere. */
  limitation: string;
  /** Suggested next step — a test/investigation, never a definitive "increase/decrease budget" directive. null for purely descriptive (non-actionable) items. */
  action: string | null;
  /** The indicator to keep watching after acting on this finding. null alongside a null `action`. */
  watchIndicator: string | null;
};

export type StrategicInsights = {
  periodLabel: string;
  hasComparison: boolean;
  hasData: boolean;
  /** Where this analysis came from — always "rules" in this deployment (no generative AI provider configured). Kept as a field, not a hardcoded UI string, so a future AI-backed engine can report "ai" instead without every consumer re-deciding how to label it. */
  source: "rules";
  /** One-line framing of what's in scope (how many campaigns, how many clients, which objective groups, how many days) — read this before the sections below, since it's what makes "compared only within the same client/objective" legible instead of implicit. */
  scopeNote: string;
  summary: InsightItem[];
  changes: InsightItem[];
  attention: InsightItem[];
  opportunities: InsightItem[];
  nextActions: InsightItem[];
  flaggedCampaignIds: string[];
  /** Global methodology/disclaimer note — kept in addition to each item's own `limitation`, not instead of it. */
  limitations: string;
};

const METHODOLOGY =
  "Análise estratégica gerada por um mecanismo de regras estatísticas sobre os dados exibidos no painel — nenhum modelo de IA generativa está configurado nesta instalação (veja a aba Integrações para o que falta para ativar um). Cada campanha é comparada apenas com campanhas do mesmo cliente e do mesmo grupo de objetivo; a análise nunca deduz vendas, receita, lucro ou retorno a partir de cliques ou conversas, e nunca usa metas ou benchmarks externos ao que está no painel. Trate os pontos abaixo como hipóteses a validar, não como conclusões definitivas — não considera sazonalidade, criativos, concorrência ou contexto de mercado.";

// Confidence gates — every comparison below must clear all of the ones that
// apply to it before it's allowed to become a finding. These are
// deliberately conservative: a false "no finding" is a missed hypothesis,
// a false finding shown with unwarranted confidence is a wrong steer.
const MIN_IMPRESSIONS_FOR_RATE_SIGNAL = 1000;
const MIN_CLICKS_FOR_RATE_SIGNAL = 30;
const MIN_CONVERSATIONS_FOR_COST_SIGNAL = 10;
const MIN_SPEND_SHARE_FOR_SIGNAL = 0.03; // 3% of the comparison group's own spend
const MIN_PERIOD_DAYS_FOR_SPIKE = 4; // a "spike" needs a baseline of more than a couple of days
const MIN_PERIOD_DAYS_FOR_CONFIDENCE = 7; // below this, every deviation-based finding gets an extra short-period caveat
const LOW_SHARE_FOR_OPPORTUNITY = 0.15; // "receives little budget relative to the group"
const CONCENTRATION_THRESHOLD = 0.5; // one campaign holding >50% of ITS OWN CLIENT's investment
const DEVIATION_MULTIPLIER = 1.5; // "50% worse than the group's own average"
const OPPORTUNITY_BETTER_MULTIPLIER = 0.7; // "30% better than the group's own average"

// `allowedMetrics` mirrors the same permission set the dashboard/PDF use for
// KPI columns (see client-permissions.ts). undefined means "no restriction"
// (the live Dashboard's own calls, which pass nothing) — every check below
// must treat that as fully unrestricted so existing behavior never changes.
// A metric that's disallowed is skipped everywhere it would appear, directly
// or as the basis of a comparison/derived value — never just relabeled.
function isMetricAllowed(allowed: ReadonlySet<KpiId> | undefined, id: KpiId): boolean {
  return !allowed || allowed.has(id);
}

function periodLabel(range: { since: string; until: string }): string {
  return `${formatShortDate(range.since)} a ${formatShortDate(range.until)}`;
}

function daysBetween(range: { since: string; until: string }): number {
  const since = new Date(`${range.since}T00:00:00Z`).getTime();
  const until = new Date(`${range.until}T00:00:00Z`).getTime();
  return Math.round((until - since) / 86_400_000) + 1;
}

function campaignTotals(c: CampaignInsight): Totals {
  return {
    spend: c.spend,
    impressions: c.impressions,
    clicks: c.clicks,
    linkClicks: c.linkClicks,
    conversations: c.conversations,
    reach: c.reach,
    purchases: c.purchases,
    purchaseValue: c.purchaseValue,
    leads: c.leads,
    addToCart: c.addToCart,
    completeRegistrations: c.completeRegistrations,
    postEngagement: c.postEngagement,
    videoViews: c.videoViews,
    videoCompletions: c.videoCompletions,
    outboundClicks: c.outboundClicks,
    uniqueClicks: c.uniqueClicks,
    estimatedAdRecallers: c.estimatedAdRecallers,
  };
}

// ---------------------------------------------------------------------------
// Grouping — the unit every performance comparison happens within: one
// client's own campaigns that share a compatible objective. A bucket with
// fewer than 2 campaigns has nothing to compare against, so it's simply
// skipped wherever it's used (never padded into a comparison against
// something it isn't actually comparable to).
// ---------------------------------------------------------------------------

type Bucket = { accountId: string; accountName: string; group: ObjectiveGroup; campaigns: CampaignInsight[] };

function buildBuckets(campaigns: CampaignInsight[]): Bucket[] {
  const map = new Map<string, Bucket>();
  for (const c of campaigns) {
    const group = objectiveGroup(c.objective);
    const key = `${c.accountId}::${group}`;
    const bucket = map.get(key) ?? { accountId: c.accountId, accountName: c.accountName, group, campaigns: [] };
    bucket.campaigns.push(c);
    map.set(key, bucket);
  }
  return [...map.values()];
}

// ---------------------------------------------------------------------------
// The one indicator that represents "resultado" for a given objective group
// — a cost-type metric (lower is always better here), chosen so it's never
// cost-per-conversation for an awareness campaign and never a fabricated
// conversion metric for an objective this dashboard can't measure from
// `actions`. Returns null when the metric's own denominator is unavailable
// (e.g. zero impressions) or the group has no appropriate indicator at all.
// ---------------------------------------------------------------------------

type GroupMetric = { value: number; label: string; format: (n: number) => string; volumeOk: boolean; volumeNote: string };

function groupMetricFor(
  group: ObjectiveGroup,
  totals: Totals,
  volume: { impressions: number; clicks: number },
  allowed: ReadonlySet<KpiId> | undefined
): GroupMetric | null {
  switch (group) {
    case "awareness": {
      if (!isMetricAllowed(allowed, "cpm")) return null;
      const v = cpm(totals);
      if (v === null) return null;
      return {
        value: v,
        label: "CPM",
        format: formatCurrencyBRL,
        volumeOk: volume.impressions >= MIN_IMPRESSIONS_FOR_RATE_SIGNAL,
        volumeNote: `${formatInteger(volume.impressions)} impressões`,
      };
    }
    case "messages": {
      if (!isMetricAllowed(allowed, "costPerConversation")) return null;
      const v = costPerConversation(totals);
      if (v === null) return null;
      const conversations = totals.conversations ?? 0;
      return {
        value: v,
        label: "Custo por conversa iniciada",
        format: formatCurrencyBRL,
        volumeOk: conversations >= MIN_CONVERSATIONS_FOR_COST_SIGNAL,
        volumeNote: `${formatInteger(conversations)} conversas iniciadas`,
      };
    }
    case "traffic":
    case "engagement":
    case "conversion-other": {
      if (!isMetricAllowed(allowed, "cpc")) return null;
      const v = cpc(totals);
      if (v === null) return null;
      return {
        value: v,
        label: "CPC",
        format: formatCurrencyBRL,
        volumeOk: volume.clicks >= MIN_CLICKS_FOR_RATE_SIGNAL && volume.impressions >= MIN_IMPRESSIONS_FOR_RATE_SIGNAL,
        volumeNote: `${formatInteger(volume.clicks)} cliques`,
      };
    }
    case "unknown":
      return null;
  }
}

function evaluateCampaignVsBucket(
  c: CampaignInsight,
  bucketTotals: Totals,
  bucket: Bucket,
  multiAccount: boolean,
  bucketLabel: string,
  period: string,
  shortPeriodNote: string | null,
  allowed: ReadonlySet<KpiId> | undefined
): { attention?: InsightItem; opportunity?: InsightItem } {
  const spendAllowed = isMetricAllowed(allowed, "spend");
  const spendShare = bucketTotals.spend > 0 ? c.spend / bucketTotals.spend : 0;
  const cMetric = groupMetricFor(bucket.group, campaignTotals(c), { impressions: c.impressions, clicks: c.clicks }, allowed);
  const bucketMetric = groupMetricFor(bucket.group, bucketTotals, { impressions: bucketTotals.impressions, clicks: bucketTotals.clicks }, allowed);
  if (!cMetric || !bucketMetric || !cMetric.volumeOk) return {};

  const namePrefix = multiAccount ? `${c.accountName} · ${c.campaignName}` : c.campaignName;
  const commercialCaveat =
    bucket.group === "messages"
      ? "Custo por conversa iniciada mede o custo para começar um contato, não a qualidade da conversa nem um resultado comercial (venda, receita ou retorno)."
      : "Este indicador mede custo/entrega, não vendas, receita, lucro ou retorno — não é possível concluir resultado comercial só a partir dele.";
  const result: { attention?: InsightItem; opportunity?: InsightItem } = {};

  if (spendShare >= MIN_SPEND_SHARE_FOR_SIGNAL && cMetric.value > bucketMetric.value * DEVIATION_MULTIPLIER) {
    const deltaPct = pctChange(cMetric.value, bucketMetric.value);
    result.attention = {
      text: `${namePrefix}: ${cMetric.label} de ${cMetric.format(cMetric.value)}${
        deltaPct !== null ? `, ${formatSignedPercent(deltaPct)}` : ""
      } em relação à média do grupo de ${bucketLabel} (${cMetric.format(bucketMetric.value)}), com base em ${cMetric.volumeNote}.`,
      evidence: [
        { label: `${cMetric.label} da campanha`, value: cMetric.format(cMetric.value) },
        { label: `${cMetric.label} médio do grupo`, value: cMetric.format(bucketMetric.value) },
        ...(spendAllowed ? [{ label: "Investimento da campanha", value: formatCurrencyBRL(c.spend) }] : []),
      ],
      period,
      limitation: `Comparado apenas com outras campanhas de ${bucketLabel} deste mesmo cliente — nunca com outro cliente ou objetivo. ${commercialCaveat}${shortPeriodNote ? ` ${shortPeriodNote}` : ""}`,
      action: "Revisar criativo, público e configuração desta campanha frente às demais do mesmo grupo.",
      watchIndicator: cMetric.label,
    };
  }

  if (spendShare < LOW_SHARE_FOR_OPPORTUNITY && cMetric.value < bucketMetric.value * OPPORTUNITY_BETTER_MULTIPLIER) {
    result.opportunity = {
      text: `${namePrefix} tem ${cMetric.label} de ${cMetric.format(cMetric.value)} (mais eficiente que a média de ${bucketLabel}, ${cMetric.format(
        bucketMetric.value
      )})${spendAllowed ? `, mas responde por apenas ${formatPercent(spendShare * 100)} do investimento do grupo` : ""}, com base em ${cMetric.volumeNote}.`,
      evidence: [
        { label: `${cMetric.label} da campanha`, value: cMetric.format(cMetric.value) },
        { label: `${cMetric.label} médio do grupo`, value: cMetric.format(bucketMetric.value) },
        ...(spendAllowed ? [{ label: "Participação no investimento do grupo", value: formatPercent(spendShare * 100) }] : []),
      ],
      period,
      limitation: `Resultado isolado dentro do grupo de ${bucketLabel} — a amostra ainda é pequena frente ao grupo, e ${cMetric.label} não mede vendas, receita ou retorno. Não é uma campanha "vencedora", é uma hipótese a validar.${shortPeriodNote ? ` ${shortPeriodNote}` : ""}`,
      action: "Considerar um teste controlado, com aumento gradual de orçamento, acompanhando se o indicador se mantém estável.",
      watchIndicator: cMetric.label,
    };
  }

  return result;
}

// ---------------------------------------------------------------------------
// Summary / changes — factual reporting of totals. Never a judgement call
// between clients: when more than one client is in scope, the per-client
// breakdown is presented side by side with an explicit note that it's not a
// ranking, exactly to head off "different budgets = one client's problem".
// ---------------------------------------------------------------------------

function buildSummary(
  totals: Totals,
  label: string,
  campaigns: CampaignInsight[],
  multiAccount: boolean,
  accountNames: Map<string, string>,
  allowed: ReadonlySet<KpiId> | undefined
): InsightItem[] {
  const spendAllowed = isMetricAllowed(allowed, "spend");
  const impressionsAllowed = isMetricAllowed(allowed, "impressions");
  const clicksAllowed = isMetricAllowed(allowed, "clicks");
  const ctrAllowed = isMetricAllowed(allowed, "ctr");
  const totalCtr = ctr(totals);

  const clauses: string[] = [];
  if (spendAllowed) clauses.push(`investimento total de ${formatCurrencyBRL(totals.spend)}`);
  if (impressionsAllowed) clauses.push(`${formatInteger(totals.impressions)} impressões`);
  if (clicksAllowed) clauses.push(`${formatInteger(totals.clicks)} cliques${ctrAllowed && totalCtr !== null ? ` (CTR de ${formatPercent(totalCtr)})` : ""}`);

  const evidence: InsightEvidence[] = [];
  if (spendAllowed) evidence.push({ label: "Investimento", value: formatCurrencyBRL(totals.spend) });
  if (impressionsAllowed) evidence.push({ label: "Impressões", value: formatInteger(totals.impressions) });
  if (clicksAllowed) evidence.push({ label: "Cliques", value: formatInteger(totals.clicks) });

  const summaryText =
    clauses.length === 0
      ? `Nenhum indicador autorizado para exibição do resumo no período de ${label}.`
      : `${clauses[0].charAt(0).toUpperCase()}${clauses[0].slice(1)} no período de ${label}${
          clauses.length > 1 ? `, gerando ${clauses.slice(1).join(" e ")}` : ""
        }.`;

  const items: InsightItem[] = [
    {
      text: summaryText,
      evidence,
      period: label,
      limitation:
        "Total consolidado do filtro atual — quando há mais de um cliente ou grupo de objetivo selecionado, use os Pontos de atenção e Oportunidades para comparações, que são sempre feitas dentro do mesmo cliente e objetivo, nunca contra este total combinado.",
      action: null,
      watchIndicator: null,
    },
  ];

  if (multiAccount && spendAllowed) {
    const byAccount = new Map<string, number>();
    for (const c of campaigns) byAccount.set(c.accountId, (byAccount.get(c.accountId) ?? 0) + c.spend);
    const parts = [...byAccount.entries()].map(([id, spend]) => `${accountNames.get(id) ?? id}: ${formatCurrencyBRL(spend)}`).join(" · ");
    items.push({
      text: `Investimento por cliente no período: ${parts}.`,
      evidence: [...byAccount.entries()].map(([id, spend]) => ({ label: accountNames.get(id) ?? id, value: formatCurrencyBRL(spend) })),
      period: label,
      limitation:
        "Apenas descritivo — diferenças de orçamento entre clientes refletem estratégias e contratos distintos, não uma comparação de desempenho entre eles.",
      action: null,
      watchIndicator: null,
    });
  }

  return items;
}

function buildChanges(
  campaigns: CampaignInsight[],
  comparisonCampaigns: CampaignInsight[],
  multiAccount: boolean,
  accountNames: Map<string, string>,
  label: string,
  allowed: ReadonlySet<KpiId> | undefined
): InsightItem[] {
  if (!isMetricAllowed(allowed, "spend")) {
    return [
      {
        text: "Comparação com o período anterior indisponível: o indicador de investimento não está autorizado para exibição neste relatório.",
        evidence: [],
        period: label,
        limitation: "",
        action: null,
        watchIndicator: null,
      },
    ];
  }

  if (!multiAccount) {
    const totals = sumTotals(campaigns);
    const prevTotals = sumTotals(comparisonCampaigns);
    const spendChange = pctChange(totals.spend, prevTotals.spend);
    return [
      {
        text:
          spendChange === null
            ? `Sem investimento no período anterior para comparação (período atual: ${formatCurrencyBRL(totals.spend)}).`
            : `O investimento foi ${formatSignedPercent(spendChange)} em relação ao período anterior (${formatCurrencyBRL(
                prevTotals.spend
              )} → ${formatCurrencyBRL(totals.spend)}).`,
        evidence: [
          { label: "Período atual", value: formatCurrencyBRL(totals.spend) },
          { label: "Período anterior", value: formatCurrencyBRL(prevTotals.spend) },
        ],
        period: label,
        limitation:
          spendChange === null
            ? "Sem período anterior comparável — pode ser uma campanha ou cliente novo no painel, não uma queda a zero."
            : "Variação de investimento não implica, por si só, variação proporcional de resultado — confira os indicadores de cada grupo de objetivo separadamente.",
        action: null,
        watchIndicator: "Investimento",
      },
    ];
  }

  const accountIds = new Set([...campaigns.map((c) => c.accountId), ...comparisonCampaigns.map((c) => c.accountId)]);
  const items: InsightItem[] = [];
  for (const accountId of accountIds) {
    const cur = sumTotals(campaigns.filter((c) => c.accountId === accountId));
    const prev = sumTotals(comparisonCampaigns.filter((c) => c.accountId === accountId));
    if (cur.spend === 0 && prev.spend === 0) continue;
    const delta = pctChange(cur.spend, prev.spend);
    const name = accountNames.get(accountId) ?? accountId;
    items.push({
      text:
        delta === null
          ? `${name}: sem investimento no período anterior para comparação (período atual: ${formatCurrencyBRL(cur.spend)}).`
          : `${name}: investimento ${formatSignedPercent(delta)} em relação ao período anterior (${formatCurrencyBRL(prev.spend)} → ${formatCurrencyBRL(
              cur.spend
            )}).`,
      evidence: [
        { label: "Período atual", value: formatCurrencyBRL(cur.spend) },
        { label: "Período anterior", value: formatCurrencyBRL(prev.spend) },
      ],
      period: label,
      limitation: "Comparado apenas com o período anterior do próprio cliente — nunca com outro cliente do filtro atual.",
      action: null,
      watchIndicator: "Investimento",
    });
  }
  return items;
}

function buildScopeNote(
  campaigns: CampaignInsight[],
  accountIds: Set<string>,
  accountNames: Map<string, string>,
  objectiveGroups: Set<ObjectiveGroup>,
  periodDays: number
): string {
  const accountList = [...accountIds].map((id) => accountNames.get(id) ?? id).join(", ");
  const groupList = [...objectiveGroups].map((g) => OBJECTIVE_GROUP_LABEL[g]).join(", ");
  const periodDaysLabel = `${periodDays} dia${periodDays === 1 ? "" : "s"}`;
  return `${campaigns.length} campanha${campaigns.length === 1 ? "" : "s"} no filtro atual, de ${accountIds.size} cliente${
    accountIds.size === 1 ? "" : "s"
  } (${accountList}), período de ${periodDaysLabel}, objetivo(s): ${groupList}. As comparações de desempenho abaixo são sempre dentro do mesmo cliente e do mesmo grupo de objetivo.`;
}

function buildNextActions(attention: InsightItem[], opportunities: InsightItem[]): InsightItem[] {
  const fromAttention = attention
    .filter((a) => a.action)
    .slice(0, 3)
    .map((a) => ({ ...a, text: `Investigar: ${a.text}` }));
  const fromOpportunities = opportunities
    .filter((o) => o.action)
    .slice(0, 2)
    .map((o) => ({ ...o, text: `Avaliar: ${o.text}` }));
  return [...fromAttention, ...fromOpportunities].slice(0, 5);
}

// ---------------------------------------------------------------------------

export function computeStrategicInsights(input: {
  campaigns: CampaignInsight[];
  comparisonCampaigns: CampaignInsight[] | null;
  daily: { date: string; spend: number }[];
  resolvedRange: { since: string; until: string };
  partialAccountNames: string[];
  /** Metric ids authorized for the requesting recipient — undefined (the live Dashboard's own calls) means unrestricted. When set, every finding, comparison and derived text below is gated to never mention a metric outside this set. */
  allowedMetrics?: ReadonlySet<KpiId>;
}): StrategicInsights {
  const { campaigns, comparisonCampaigns, daily, resolvedRange, partialAccountNames, allowedMetrics } = input;
  const label = periodLabel(resolvedRange);
  const periodDays = daysBetween(resolvedRange);

  if (campaigns.length === 0) {
    return {
      periodLabel: label,
      hasComparison: comparisonCampaigns !== null,
      hasData: false,
      source: "rules",
      scopeNote: `Nenhuma campanha no filtro atual para o período de ${label}.`,
      summary: [{ text: `Nenhuma campanha com investimento no período de ${label} para os filtros atuais.`, evidence: [], period: label, limitation: "", action: null, watchIndicator: null }],
      changes: [],
      attention: [],
      opportunities: [],
      nextActions: [],
      flaggedCampaignIds: [],
      limitations: METHODOLOGY,
    };
  }

  const totals = sumTotals(campaigns);
  const accountIds = new Set(campaigns.map((c) => c.accountId));
  const accountNames = new Map(campaigns.map((c) => [c.accountId, c.accountName]));
  const multiAccount = accountIds.size > 1;
  const objectiveGroups = new Set(campaigns.map((c) => objectiveGroup(c.objective)));
  const shortPeriod = periodDays < MIN_PERIOD_DAYS_FOR_CONFIDENCE;
  const shortPeriodNote = shortPeriod
    ? `Período de apuração curto (${periodDays} dia${periodDays === 1 ? "" : "s"}) — variações podem refletir o dia a dia, não uma tendência.`
    : null;

  const scopeNote = buildScopeNote(campaigns, accountIds, accountNames, objectiveGroups, periodDays);
  const summary = buildSummary(totals, label, campaigns, multiAccount, accountNames, allowedMetrics);
  const changes = comparisonCampaigns
    ? buildChanges(campaigns, comparisonCampaigns, multiAccount, accountNames, label, allowedMetrics)
    : [
        {
          text: "Comparação com o período anterior não está ativada — ative o filtro de comparação para ver as principais mudanças.",
          evidence: [],
          period: label,
          limitation: "",
          action: null,
          watchIndicator: null,
        },
      ];

  const attention: InsightItem[] = [];
  const opportunities: InsightItem[] = [];
  const flagged = new Set<string>();

  if (partialAccountNames.length > 0) {
    attention.push({
      text: `${partialAccountNames.length} conta(s) não puderam ser carregadas neste momento (${partialAccountNames.join(
        ", "
      )}) — os totais acima estão incompletos, não zerados.`,
      evidence: [],
      period: label,
      limitation: "Reflete uma falha temporária de carregamento, não um resultado real de zero.",
      action: "Recarregar o painel em instantes e confirmar se os dados permanecem incompletos.",
      watchIndicator: "Contas conectadas",
    });
  }

  // Per-(client, objective group) deviation checks — see evaluateCampaignVsBucket's
  // own comments for why each check is gated the way it is.
  for (const bucket of buildBuckets(campaigns)) {
    if (bucket.campaigns.length < 2 || bucket.group === "unknown") continue; // nothing to compare a single campaign (or an unclassified objective) against
    const bucketTotals = sumTotals(bucket.campaigns);
    const bucketLabel = multiAccount ? `${bucket.accountName} · ${OBJECTIVE_GROUP_LABEL[bucket.group]}` : OBJECTIVE_GROUP_LABEL[bucket.group];
    for (const c of bucket.campaigns) {
      const { attention: a, opportunity: o } = evaluateCampaignVsBucket(c, bucketTotals, bucket, multiAccount, bucketLabel, label, shortPeriodNote, allowedMetrics);
      if (a) {
        attention.push(a);
        flagged.add(c.campaignId);
      }
      if (o) opportunities.push(o);
    }
  }

  // Concentration — evaluated per client, on that client's own spend only,
  // and only when the client has at least 2 campaigns in view (a single
  // filtered campaign is trivially "100%" and that's not a finding).
  // Skipped entirely when "spend" itself isn't authorized, since every part
  // of this finding (share, evidence) is derived from spend values.
  for (const accountId of isMetricAllowed(allowedMetrics, "spend") ? accountIds : []) {
    const accCampaigns = campaigns.filter((c) => c.accountId === accountId);
    if (accCampaigns.length < 2) continue;
    const accSpend = accCampaigns.reduce((s, c) => s + c.spend, 0);
    if (accSpend <= 0) continue;
    const top = [...accCampaigns].sort((a, b) => b.spend - a.spend)[0];
    const share = top.spend / accSpend;
    if (share > CONCENTRATION_THRESHOLD) {
      const accountName = accountNames.get(accountId) ?? accountId;
      opportunities.push({
        text: `Em ${accountName}, ${formatPercent(share * 100)} do investimento do período está concentrado em uma única campanha (${
          top.campaignName
        }), entre as ${accCampaigns.length} campanhas ativas desse cliente no filtro atual.`,
        evidence: [
          { label: "Campanha", value: top.campaignName },
          { label: "Participação no investimento do cliente", value: formatPercent(share * 100) },
          { label: "Campanhas ativas do cliente no filtro", value: formatInteger(accCampaigns.length) },
        ],
        period: label,
        limitation:
          "Concentração não é necessariamente um problema — pode ser uma estratégia deliberada. A comparação é só entre as campanhas deste cliente, nunca contra o orçamento de outros clientes do filtro.",
        action: "Confirmar se a concentração é intencional; se não for, avaliar redistribuir entre as demais campanhas ativas deste cliente.",
        watchIndicator: "Participação da campanha no investimento do cliente",
      });
    }
  }

  // Daily spend spikes — an aggregate-trend observation (not a cross-client
  // comparison), so it's fine to look at the combined series; just needs
  // enough days to have a baseline average worth comparing against. Skipped
  // when "spend" isn't authorized, since the finding is entirely spend values.
  if (isMetricAllowed(allowedMetrics, "spend") && periodDays >= MIN_PERIOD_DAYS_FOR_SPIKE && daily.length > 1) {
    const avgDaily = daily.reduce((s, d) => s + d.spend, 0) / daily.length;
    const spikes = daily.filter((d) => avgDaily > 0 && d.spend > avgDaily * 2).slice(0, 2);
    for (const spike of spikes) {
      attention.push({
        text: `Pico de investimento em ${formatShortDate(spike.date)}: ${formatCurrencyBRL(spike.spend)}, frente a uma média diária de ${formatCurrencyBRL(
          avgDaily
        )} no período${multiAccount ? " (valor agregado entre os clientes selecionados)" : ""}.`,
        evidence: [
          { label: "Investimento no dia", value: formatCurrencyBRL(spike.spend) },
          { label: "Média diária do período", value: formatCurrencyBRL(avgDaily) },
        ],
        period: label,
        limitation: "Um pico pontual não indica por si só um problema — pode refletir um ajuste de orçamento, criativo novo ou sazonalidade do dia.",
        action: "Confirmar se o pico foi intencional e, se não, revisar a configuração da campanha nesse dia.",
        watchIndicator: "Investimento diário",
      });
    }
  }

  const cappedAttention = attention.slice(0, 6);
  const cappedOpportunities = opportunities.slice(0, 5);
  const nextActions = buildNextActions(cappedAttention, cappedOpportunities);

  return {
    periodLabel: label,
    hasComparison: comparisonCampaigns !== null,
    hasData: true,
    source: "rules",
    scopeNote,
    summary,
    changes,
    attention: cappedAttention,
    opportunities: cappedOpportunities,
    nextActions,
    flaggedCampaignIds: [...flagged],
    limitations: METHODOLOGY,
  };
}
