// Rule-based "leitura estratégica" engine. This is deliberately NOT an LLM
// call — there's no AI model wired into this project (no API key, no
// backend route for it). Every sentence here is generated by simple,
// inspectable statistical rules over the numbers already on screen, and the
// UI must always label it as automatic/rule-based rather than presenting it
// as an active AI. See docs/meta-ads-setup.md for what a real generative-AI
// upgrade of this block would require.

import type { CampaignInsight } from "./meta-ads-types";
import { sumTotals, ctr, cpc, costPerConversation, pctChange, type Totals } from "./metrics";
import { formatCurrencyBRL, formatInteger, formatPercent, formatSignedPercent, formatShortDate } from "./format";

export type InsightEvidence = { label: string; value: string };
export type InsightItem = { text: string; evidence: InsightEvidence[] };

export type StrategicInsights = {
  periodLabel: string;
  hasComparison: boolean;
  hasData: boolean;
  summary: InsightItem[];
  attention: InsightItem[];
  opportunities: InsightItem[];
  nextActions: InsightItem[];
  flaggedCampaignIds: string[];
  limitations: string;
};

const LIMITATIONS =
  "Análise automática gerada por regras estatísticas simples sobre os dados exibidos (sem uso de um modelo de IA generativa). Não considera sazonalidade, criativos, concorrência ou contexto de mercado — trate os pontos abaixo como hipóteses a validar, não como conclusões definitivas.";

const MIN_IMPRESSIONS_FOR_CTR_SIGNAL = 500;
const MIN_SPEND_SHARE_FOR_CPC_SIGNAL = 0.03; // 3% of total spend
const CONCENTRATION_THRESHOLD = 0.5; // one campaign holding >50% of spend

function periodLabel(range: { since: string; until: string }): string {
  return `${formatShortDate(range.since)} a ${formatShortDate(range.until)}`;
}

function campaignTotals(c: CampaignInsight): Totals {
  return { spend: c.spend, impressions: c.impressions, clicks: c.clicks, linkClicks: c.linkClicks, reach: c.reach };
}

export function computeStrategicInsights(input: {
  campaigns: CampaignInsight[];
  comparisonCampaigns: CampaignInsight[] | null;
  daily: { date: string; spend: number }[];
  resolvedRange: { since: string; until: string };
  partialAccountNames: string[];
}): StrategicInsights {
  const { campaigns, comparisonCampaigns, daily, resolvedRange, partialAccountNames } = input;
  const label = periodLabel(resolvedRange);

  if (campaigns.length === 0) {
    return {
      periodLabel: label,
      hasComparison: comparisonCampaigns !== null,
      hasData: false,
      summary: [
        {
          text: `Nenhuma campanha com investimento no período de ${label} para os filtros atuais.`,
          evidence: [],
        },
      ],
      attention: [],
      opportunities: [],
      nextActions: [],
      flaggedCampaignIds: [],
      limitations: LIMITATIONS,
    };
  }

  const totals = sumTotals(campaigns);
  const totalCtr = ctr(totals);
  const totalCpc = cpc(totals);
  const totalCostPerConversation = costPerConversation(totals);

  const summary: InsightItem[] = [
    {
      text: `Investimento total de ${formatCurrencyBRL(totals.spend)} no período de ${label}, gerando ${formatInteger(
        totals.impressions
      )} impressões e ${formatInteger(totals.clicks)} cliques${totalCtr !== null ? ` (CTR de ${formatPercent(totalCtr)})` : ""}.`,
      evidence: [
        { label: "Investimento", value: formatCurrencyBRL(totals.spend) },
        { label: "Impressões", value: formatInteger(totals.impressions) },
        { label: "Cliques", value: formatInteger(totals.clicks) },
      ],
    },
  ];

  if (comparisonCampaigns) {
    const prevTotals = sumTotals(comparisonCampaigns);
    const spendChange = pctChange(totals.spend, prevTotals.spend);
    summary.push({
      text:
        spendChange === null
          ? `Sem investimento no período anterior para comparação (período atual: ${formatCurrencyBRL(totals.spend)}).`
          : `O investimento foi ${formatSignedPercent(spendChange)} em relação ao período anterior (${formatCurrencyBRL(
              prevTotals.spend
            )}).`,
      evidence: [
        { label: "Período atual", value: formatCurrencyBRL(totals.spend) },
        { label: "Período anterior", value: formatCurrencyBRL(prevTotals.spend) },
      ],
    });
  } else {
    summary.push({
      text: "Comparação com o período anterior não está ativada — ative o filtro de comparação para ver a variação.",
      evidence: [],
    });
  }

  const attention: InsightItem[] = [];
  const opportunities: InsightItem[] = [];
  const flagged = new Set<string>();

  if (partialAccountNames.length > 0) {
    attention.push({
      text: `${partialAccountNames.length} conta(s) não puderam ser carregadas neste momento (${partialAccountNames.join(
        ", "
      )}) — os totais acima estão incompletos, não zerados.`,
      evidence: [],
    });
  }

  // Per-campaign deviations vs. the account's own weighted average — never
  // vs. a fixed external benchmark, since accounts and objectives differ.
  for (const c of campaigns) {
    const spendShare = totals.spend > 0 ? c.spend / totals.spend : 0;
    const cCtr = ctr(campaignTotals(c));
    const cCpc = cpc(campaignTotals(c));
    const cCostPerConversation = costPerConversation(campaignTotals(c));

    if (
      cCpc !== null &&
      totalCpc !== null &&
      spendShare >= MIN_SPEND_SHARE_FOR_CPC_SIGNAL &&
      cCpc > totalCpc * 1.5
    ) {
      attention.push({
        text: `${c.campaignName}: CPC de ${formatCurrencyBRL(cCpc)}, ${formatSignedPercent(
          pctChange(cCpc, totalCpc) ?? 0
        )} em relação ao CPC médio do período (${formatCurrencyBRL(totalCpc)}).`,
        evidence: [
          { label: "CPC da campanha", value: formatCurrencyBRL(cCpc) },
          { label: "CPC médio do período", value: formatCurrencyBRL(totalCpc) },
          { label: "Investimento da campanha", value: formatCurrencyBRL(c.spend) },
        ],
      });
      flagged.add(c.campaignId);
    }

    if (
      cCostPerConversation !== null &&
      totalCostPerConversation !== null &&
      spendShare >= MIN_SPEND_SHARE_FOR_CPC_SIGNAL &&
      cCostPerConversation > totalCostPerConversation * 1.5
    ) {
      attention.push({
        text: `${c.campaignName}: custo por conversa iniciada de ${formatCurrencyBRL(cCostPerConversation)}, ${formatSignedPercent(
          pctChange(cCostPerConversation, totalCostPerConversation) ?? 0
        )} em relação à média do período (${formatCurrencyBRL(totalCostPerConversation)}).`,
        evidence: [
          { label: "Custo/conversa da campanha", value: formatCurrencyBRL(cCostPerConversation) },
          { label: "Custo/conversa médio do período", value: formatCurrencyBRL(totalCostPerConversation) },
          { label: "Investimento da campanha", value: formatCurrencyBRL(c.spend) },
        ],
      });
      flagged.add(c.campaignId);
    }

    if (
      cCtr !== null &&
      totalCtr !== null &&
      c.impressions >= MIN_IMPRESSIONS_FOR_CTR_SIGNAL &&
      cCtr < totalCtr * 0.5
    ) {
      attention.push({
        text: `${c.campaignName}: CTR de ${formatPercent(cCtr)}, abaixo da média do período (${formatPercent(totalCtr)}), com ${formatInteger(
          c.impressions
        )} impressões.`,
        evidence: [
          { label: "CTR da campanha", value: formatPercent(cCtr) },
          { label: "CTR médio do período", value: formatPercent(totalCtr) },
          { label: "Impressões", value: formatInteger(c.impressions) },
        ],
      });
      flagged.add(c.campaignId);
    }

    if (
      cCpc !== null &&
      totalCpc !== null &&
      cCtr !== null &&
      totalCtr !== null &&
      cCpc < totalCpc * 0.7 &&
      cCtr > totalCtr * 1.2 &&
      spendShare < 0.15 &&
      c.impressions >= MIN_IMPRESSIONS_FOR_CTR_SIGNAL
    ) {
      opportunities.push({
        text: `${c.campaignName} tem CPC ${formatCurrencyBRL(cCpc)} (abaixo da média) e CTR ${formatPercent(
          cCtr
        )} (acima da média), mas responde por apenas ${formatPercent(spendShare * 100)} do investimento — pode ser candidata a receber mais orçamento (hipótese a validar).`,
        evidence: [
          { label: "CPC da campanha", value: formatCurrencyBRL(cCpc) },
          { label: "CTR da campanha", value: formatPercent(cCtr) },
          { label: "Participação no investimento", value: formatPercent(spendShare * 100) },
        ],
      });
    }
  }

  const topCampaign = campaigns[0];
  const topShare = totals.spend > 0 ? topCampaign.spend / totals.spend : 0;
  if (topShare > CONCENTRATION_THRESHOLD) {
    opportunities.push({
      text: `${formatPercent(topShare * 100)} do investimento do período está concentrado em uma única campanha (${
        topCampaign.campaignName
      }) — vale avaliar a exposição a essa concentração.`,
      evidence: [
        { label: "Campanha", value: topCampaign.campaignName },
        { label: "Participação no investimento", value: formatPercent(topShare * 100) },
      ],
    });
  }

  // Daily spend spikes
  if (daily.length > 1) {
    const avgDaily = daily.reduce((s, d) => s + d.spend, 0) / daily.length;
    const spikes = daily.filter((d) => avgDaily > 0 && d.spend > avgDaily * 2).slice(0, 2);
    for (const spike of spikes) {
      attention.push({
        text: `Pico de investimento em ${formatShortDate(spike.date)}: ${formatCurrencyBRL(
          spike.spend
        )}, frente a uma média diária de ${formatCurrencyBRL(avgDaily)} no período.`,
        evidence: [
          { label: "Investimento no dia", value: formatCurrencyBRL(spike.spend) },
          { label: "Média diária do período", value: formatCurrencyBRL(avgDaily) },
        ],
      });
    }
  }

  const cappedAttention = attention.slice(0, 5);
  const cappedOpportunities = opportunities.slice(0, 4);

  const nextActions: InsightItem[] = [
    ...cappedAttention.slice(0, 3).map((item) => ({
      text: `Investigar: ${item.text}`,
      evidence: item.evidence,
    })),
    ...cappedOpportunities.slice(0, 2).map((item) => ({
      text: `Avaliar: ${item.text}`,
      evidence: item.evidence,
    })),
  ].slice(0, 4);

  return {
    periodLabel: label,
    hasComparison: comparisonCampaigns !== null,
    hasData: true,
    summary,
    attention: cappedAttention,
    opportunities: cappedOpportunities,
    nextActions,
    flaggedCampaignIds: [...flagged],
    limitations: LIMITATIONS,
  };
}
